Allow disabling errors
mlr-org/mlr3benchmark pull request #22
Opened 2021-08-03 21:01 UTC by pfistfl

Introduces a new arg `friedman_global` that allows disabling errors if the friedman global test does not pass for critical differences plots.

2021-08-03 21:02 UTC, pfistfl commented
Solves #21

2021-08-24 11:15 UTC, RaphaelS1 requested changes
Thanks for this, some small comments

2021-08-24 11:15 UTC, RaphaelS1 commented on R/BenchmarkAggr.R
> +      dt = map_at(dt, c(task_id, learner_id), as.factor)
I think we removed automatically converting to a factor as it easily leads to errors

2021-08-24 11:15 UTC, RaphaelS1 commented on R/BenchmarkAggr.R
> +                     warning(sprintf("Global Friedman test non-significant (p > %s), try type = 'mean' instead.", p.value)) # nolint))
I don't think we need a warning here, if `friedman_posthoc=FALSE` as default then the user should know what they're doing when they change it

2021-08-24 11:15 UTC, RaphaelS1 commented on R/autoplot.BenchmarkAggr.R
> +#' Default is `TRUE` (raises an error).
```suggestion
#' Default is `TRUE` (raises an error if global test fails).
```

2021-08-24 11:15 UTC, RaphaelS1 commented on R/autoplot.BenchmarkAggr.R
> +                     warning(sprintf("Global Friedman test non-significant (p > %s), try type = 'mean' instead.", p.value)) # nolint))
As above, I don't think the warning is needed

2021-08-24 11:15 UTC, RaphaelS1 commented on R/autoplot.BenchmarkAggr.R
> +      p = cbind(expand.grid(obj$data[[obj$col_roles$learner_id]],  obj$data[[obj$col_roles$task_id]]), value = 1)
Shouldn't `p` always equal the result of the posthoc?

2021-08-24 11:15 UTC, RaphaelS1 commented on R/BenchmarkAggr.R
> +                                test = c("bd", "nemenyi"), friedman_posthoc = TRUE) {
Seems confusingly named, shouldn't this be friedman_global?

2022-06-24 10:36 UTC, RaphaelS1 commented on R/BenchmarkAggr.R
> +      dt = map_at(dt, c(task_id, learner_id), as.factor)
```suggestion
```

2022-06-24 12:13 UTC, merged